# Generated by Django 4.2.11 on 2024-04-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_phone_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
